# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ tests ]

  pull_request:
    branches: [ master ]

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    runs-on: ubuntu-latest
    container:
      image: lorisleiva/laravel-docker:7.4
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Composer dependencies
        run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist

      - name: Run Testsuite
        run: php -d memory_limit=-1 -d xdebug.mode=coverage vendor/bin/phpunit --coverage-text --colors=never

      - name: Run php-cs-fixer
        run: vendor/bin/php-cs-fixer --dry-run -v fix
